### ISSUE TITLE
can we use jdk 1.8?

### ISSUE THREAD

**Issue by DemianTinkiel** [authzforce/java-xacml-sdk#16]
Hi @hargathor  / @cdanger,

Can we use JDK 1.8 ?  Mostly for convenience on Collection manipulation (of which there is a lot :smile: ) and use of Lambda functions

**Comment by cdanger** [comment]
I'm actually surprised we're still at java 1.7 on this project. Most other authzforce projects have upgraded. So yes, please do :-)
