### ISSUE TITLE
Administration SDK

### ISSUE THREAD

**Issue by DemianTinkiel** [authzforce/java-xacml-sdk#17]
I'd like to propose a new  AdminXacmlSdk that would allow for
- getDomain
- addDomain
- deleteDomain
- getPolicy
- addPolicy
- deletePolicy
- createSimplePolicy

**Comment by DemianTinkiel** [comment]
@cdanger / @hargathor I created #18  to show what direction I'm taking with this

**Comment by cdanger** [comment]
Good idea, but it should be a separate module. We want to keep the PDP SDK and PAP SDK (aka Admin SDK) separate, in particular to keep it light for PEPs. Because PEPs will only need the JAR for PDP SDK and should not need more.

**Comment by DemianTinkiel** [comment]
@cdanger sure, I'm on it. A question: There is the `xacml-sdk-distribution` that creates a jar-with-dependencies, shall I also add the new `xacml-sdk-admin` to it (currently only packages the `xacml-sdk-core`)?

**Comment by DemianTinkiel** [comment]
@cdanger a small deviation, can we merge dev to master after this or does this affect CI?

**Comment by cdanger** [comment]
> @cdanger sure, I'm on it. A question: There is the `xacml-sdk-distribution` that creates a jar-with-dependencies, shall I also add the new `xacml-sdk-admin` to it (currently only packages the `xacml-sdk-core`)?
> 

I would say yes. But not sure what was the purpose of the jar-with-dependencies. 
@hargathor  **what do you think?**  

> Also I'm assuming is ok to leave the `AdminXacmlSdk` API in the `authzforce-xacmlsdk-api` module or do you want to move it also to the new module?

I prefer to move it to a new module like authzforce-xacmlsdk-pap-api, and rename authzforce-xacmlsdk-api to authzforce-xacmlsdk-pdp-api to be consistent .

> @cdanger a small deviation, can we merge dev to master after this or does this affect CI?

I think @hargathor follows the gitflow on this, so dev is merged to master only in case of new release.
@hargathor **do you confirm? is the CI responsible to make new releases and merge?**

**Comment by DemianTinkiel** [comment]
> I prefer to move the API (interfaces) to a new module like authzforce-xacmlsdk-pap-api, and rename authzforce-xacmlsdk-api to authzforce-xacmlsdk-pdp-api to be consistent .

Ok, but maybe I should also change the artifact id. Currently folder is `authzforce-xacmlsdk-api` and artifactID is `<artifactId>xacml-sdk-api</artifactId>`

**Comment by DemianTinkiel** [comment]
I think the structure of the project might be a bit complicated now. For reference with these changes made it looks as follows:
```
 mvn dependency:tree -Dincludes=org.ow2.authzforce
------------------------------------------------------------------------
Reactor Build Order:

AuthZForce :: XACML SDK
AuthZForce :: XACML SDK :: MODEL
AuthZForce :: XACML SDK :: COMMON
AuthZForce :: XACML SDK :: PDP API
AuthZForce :: XACML SDK :: CORE
AuthZForce :: XACML SDK :: PAP API
AuthZForce :: XACML SDK :: ADMIN
AuthZForce :: XACML SDK :: DISTRIBUTION

------------------------------------------------------------------------
Building AuthZForce :: XACML SDK 5.0.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.8:tree (default-cli) @ xacml-sdk ---
org.ow2.authzforce:xacml-sdk:pom:5.0.0-SNAPSHOT

------------------------------------------------------------------------
Building AuthZForce :: XACML SDK :: MODEL 5.0.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.8:tree (default-cli) @ xacml-sdk-model ---
org.ow2.authzforce:xacml-sdk-model:5.0.0-SNAPSHOT
\- org.ow2.authzforce:authzforce-ce-xacml-model:3.3.7
   \- org.ow2.authzforce:authzforce-ce-xmlns-model:3.3.7

------------------------------------------------------------------------
Building AuthZForce :: XACML SDK :: COMMON 5.0.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.8:tree (default-cli) @ xacml-sdk-common ---
org.ow2.authzforce:xacml-sdk-common:5.0.0-SNAPSHOT
\- org.ow2.authzforce:xacml-sdk-model:5.0.0-SNAPSHOT
   \- org.ow2.authzforce:authzforce-ce-xacml-model:3.3.7
      \- org.ow2.authzforce:authzforce-ce-xmlns-model:3.3.7

------------------------------------------------------------------------
Building AuthZForce :: XACML SDK :: PDP API 5.0.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.8:tree (default-cli) @ xacml-sdk-api ---
org.ow2.authzforce:xacml-sdk-api:5.0.0-SNAPSHOT
+- org.ow2.authzforce:xacml-sdk-common:5.0.0-SNAPSHOT
|  \- org.ow2.authzforce:xacml-sdk-model:5.0.0-SNAPSHOT
+- org.ow2.authzforce:authzforce-ce-atom-model:7.5.1
|  \- org.ow2.authzforce:authzforce-ce-xmlns-model:3.3.7
\- org.ow2.authzforce:authzforce-ce-rest-api-model:5.7.0
   +- org.ow2.authzforce:authzforce-ce-xacml-model:3.3.7
   \- org.ow2.authzforce:authzforce-ce-pdp-ext-model:3.3.7

------------------------------------------------------------------------
Building AuthZForce :: XACML SDK :: CORE 5.0.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.8:tree (default-cli) @ xacml-sdk-core ---
org.ow2.authzforce:xacml-sdk-core:5.0.0-SNAPSHOT
+- org.ow2.authzforce:xacml-sdk-api:5.0.0-SNAPSHOT
|  \- org.ow2.authzforce:authzforce-ce-atom-model:3.3.7
|     \- org.ow2.authzforce:authzforce-ce-xmlns-model:3.3.7
+- org.ow2.authzforce:xacml-sdk-common:5.0.0-SNAPSHOT
|  \- org.ow2.authzforce:xacml-sdk-model:5.0.0-SNAPSHOT
+- org.ow2.authzforce:authzforce-ce-rest-api-model:5.7.0
|  +- org.ow2.authzforce:authzforce-ce-xacml-model:3.3.7
|  \- org.ow2.authzforce:authzforce-ce-pdp-ext-model:3.3.7
\- org.ow2.authzforce:authzforce-ce-server-rest-service:4.4.1:test
   \- org.ow2.authzforce:authzforce-ce-pap-dao-file:3.6.1:test
      +- org.ow2.authzforce:authzforce-ce-core-pap-api:3.6.0:test
      |  \- org.ow2.authzforce:authzforce-ce-core-pdp-api:3.6.1:test
      \- org.ow2.authzforce:authzforce-ce-core:3.7.0:test

------------------------------------------------------------------------
Building AuthZForce :: XACML SDK :: PAP API 5.0.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.8:tree (default-cli) @ xacml-sdk-pap-api ---
org.ow2.authzforce:xacml-sdk-pap-api:5.0.0-SNAPSHOT
\- org.ow2.authzforce:xacml-sdk-core:5.0.0-SNAPSHOT
   +- org.ow2.authzforce:xacml-sdk-api:5.0.0-SNAPSHOT
   |  \- org.ow2.authzforce:authzforce-ce-atom-model:3.3.7
   |     \- org.ow2.authzforce:authzforce-ce-xmlns-model:3.3.7
   +- org.ow2.authzforce:xacml-sdk-common:5.0.0-SNAPSHOT
   |  \- org.ow2.authzforce:xacml-sdk-model:5.0.0-SNAPSHOT
   \- org.ow2.authzforce:authzforce-ce-rest-api-model:5.7.0
      +- org.ow2.authzforce:authzforce-ce-xacml-model:3.3.7
      \- org.ow2.authzforce:authzforce-ce-pdp-ext-model:3.3.7

------------------------------------------------------------------------
Building AuthZForce :: XACML SDK :: ADMIN 5.0.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.8:tree (default-cli) @ xacml-sdk-admin ---
org.ow2.authzforce:xacml-sdk-admin:5.0.0-SNAPSHOT
+- org.ow2.authzforce:xacml-sdk-core:5.0.0-SNAPSHOT
|  +- org.ow2.authzforce:xacml-sdk-api:5.0.0-SNAPSHOT
|  |  \- org.ow2.authzforce:authzforce-ce-atom-model:3.3.7
|  |     \- org.ow2.authzforce:authzforce-ce-xmlns-model:3.3.7
|  +- org.ow2.authzforce:xacml-sdk-common:5.0.0-SNAPSHOT
|  |  \- org.ow2.authzforce:xacml-sdk-model:5.0.0-SNAPSHOT
|  \- org.ow2.authzforce:authzforce-ce-rest-api-model:5.7.0
|     +- org.ow2.authzforce:authzforce-ce-xacml-model:3.3.7
|     \- org.ow2.authzforce:authzforce-ce-pdp-ext-model:3.3.7
\- org.ow2.authzforce:xacml-sdk-pap-api:5.0.0-SNAPSHOT

------------------------------------------------------------------------
Building AuthZForce :: XACML SDK :: DISTRIBUTION 5.0.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.8:tree (default-cli) @ xacml-sdk-distribution ---
org.ow2.authzforce:xacml-sdk-distribution:pom:5.0.0-SNAPSHOT
\- org.ow2.authzforce:xacml-sdk-core:5.0.0-SNAPSHOT
   +- org.ow2.authzforce:xacml-sdk-api:5.0.0-SNAPSHOT
   |  \- org.ow2.authzforce:authzforce-ce-atom-model:3.3.7
   |     \- org.ow2.authzforce:authzforce-ce-xmlns-model:3.3.7
   +- org.ow2.authzforce:xacml-sdk-common:5.0.0-SNAPSHOT
   |  \- org.ow2.authzforce:xacml-sdk-model:5.0.0-SNAPSHOT
   \- org.ow2.authzforce:authzforce-ce-rest-api-model:5.7.0
      +- org.ow2.authzforce:authzforce-ce-xacml-model:3.3.7
      \- org.ow2.authzforce:authzforce-ce-pdp-ext-model:3.3.7
------------------------------------------------------------------------
Reactor Summary:

AuthZForce :: XACML SDK ............................ SUCCESS [  0.539 s]
AuthZForce :: XACML SDK :: MODEL ................... SUCCESS [  0.051 s]
AuthZForce :: XACML SDK :: COMMON .................. SUCCESS [  0.029 s]
AuthZForce :: XACML SDK :: PDP API ................. SUCCESS [  0.025 s]
AuthZForce :: XACML SDK :: CORE .................... SUCCESS [  0.274 s]
AuthZForce :: XACML SDK :: PAP API ................. SUCCESS [  0.022 s]
AuthZForce :: XACML SDK :: ADMIN ................... SUCCESS [  0.129 s]
AuthZForce :: XACML SDK :: DISTRIBUTION ............ SUCCESS [  0.017 s]
```

**Comment by cdanger** [comment]
Not sure what the COMMON projet is for (common to what and what?) actually, so can probably be removed, but I have to check with @hargathor .

Also we have to think of more meaningful names for CORE and ADMIN, since there are particular implementations of PDP/PAP APIs that work with AuthzForce Server's REST API. So maybe something like "RESTFUL PDP IMPL" and "RESTFUL ADMIN IMPL", I'll check with @hargathor but your opinion is welcome as well.

**Comment by DemianTinkiel** [comment]
> Not sure what the COMMON projet is for (common to what and what?) actually, so can probably be removed, but I have to check with @hargathor .

The COMMOn contains `XacmlSdkException` and `XacmlSdkExceptionCodes` used in both IMPLs

> Also we have to think of more meaningful names for CORE and ADMIN, since there are particular implementations of PDP/PAP APIs that work with AuthzForce Server's REST API. So maybe something like "RESTFUL PDP IMPL" and "RESTFUL ADMIN IMPL", I'll check with @hargathor but your opinion is welcome as well.

I know its best practice to keep API and their implementation as separate modules but doe we expect them to have multiple implementations for the same API? I would suggest keeping API and implementation in same module for PDP and PAP respectively. If someone needs to provide a different implementation they can mark theirs as `@Default` for a CDI context

**Comment by hargathor** [comment]
I'm not a big fan of merging CORE and API. This leaves no option for another implementation of the SDK. Even though there is just one right now.

**Comment by DemianTinkiel** [comment]
> I'm not a big fan of merging CORE and API. This leaves no option for another implementation of the SDK. Even though there is just one right now we can imagine more implementations in the future

I understand your concern. So in line with @cdanger  comment perhaps we should rename core and api to more meaningful names so we can do
```
org.ow2.authzforce:xacml-sdk-pdp-api
org.ow2.authzforce:xacml-sdk-pdp-impl
org.ow2.authzforce:xacml-sdk-pap-api
org.ow2.authzforce:xacml-sdk-pap-impl
```

**Comment by hargathor** [comment]
Yes this is a good idea. It will be more clear what is the purpose of each artifact

**Comment by DemianTinkiel** [comment]
@hargathor I am assuming this includes artifactID which means new release would be major e.g 5.0.0. Is that OK?

**Comment by cdanger** [comment]
OK for me. You can make a PR following this. (Later on, I will probably change the names "pdp-impl" and "pap-impl" to something more specific - after the merge to develop branch anyway - when I can think of good names to characterise these particular implementations using the REST API of AuthzForce Server. Indeed, in the future, we might have other possible future PAP implementation that manages the policies in a remote database directly for instance, using JDBC or some NoSQL API - possibly another kind of REST API - or whatever.)

**Comment by DemianTinkiel** [comment]
@cdanger if you're going to change them later on I see little point of doing it now, I rather make the change that would suite all involved.
would 
```
org.ow2.authzforce:xacml-sdk-pdp-api
org.ow2.authzforce:xacml-sdk-pdp-rest-impl
org.ow2.authzforce:xacml-sdk-pap-api
org.ow2.authzforce:xacml-sdk-pap-rest-impl
```
match suit or can there be more that a rest-impl? i.e. should I qualify it as `authzforce:xacml-sdk-pap-rest-default-impl`

**Comment by hargathor** [comment]
The naming 
```
org.ow2.authzforce:xacml-sdk-pdp-api
org.ow2.authzforce:xacml-sdk-pdp-rest-impl
org.ow2.authzforce:xacml-sdk-pap-api
org.ow2.authzforce:xacml-sdk-pap-rest-impl
```
are ok for me. Yes it will be a major version so after the merge in develop we should release a new version in master following the gitflow process

**Comment by cdanger** [comment]
yeah, it's fine, good to go.
