### ISSUE TITLE
Request schema needs updated for JSON profile of XACML 3.0 v1.1

### ISSUE THREAD

**Issue by mtrayers** [authzforce/java-xacml-sdk#29]
request attached fails validation against JSON schema.  I created the request using XACML 3.0 v1.1 format and it should pass. 

FAILED: validateXacmlJson(src\test\resources\xacml.samples\Requests\valid\MyRequest.json, true, org.testng.TestRunner@56528192)
java.lang.AssertionError: Validation against JSON schema failed but expected to pass

Looks like the schema needs updated for the Category types - Subject, Action, Resource, Environment. 

Here is the request (sorry could not upload the attachment).

{
   "Request":{     
      "AccessSubject":[{
         "Attribute":[
         	{
				"AttributeId": "urn:oasis:names:tc:xacml:1.0:subject-category:access-subject", 
				"Value": "http://example.com/buy",
				"DataType": "http://www.w3.org/2001/XMLSchema#anyURI"
			}         
         ]
      }],
      "Resource":[{
         "Attribute":[
         	{
				"AttributeId": "urn:oasis:names:tc:xacml:3.0:attribute-category:resource",
				"Value": "http://example.com/buy",
				"DataType": "http://www.w3.org/2001/XMLSchema#anyURI"
			}         
         ]
      }],
      "Action":[{
         "Attribute":[
         	{
				"AttributeId": "urn:oasis:names:tc:xacml:3.0:attribute-category:action",
				"Value": "http://example.com/buy",
				"DataType": "http://www.w3.org/2001/XMLSchema#anyURI"
			}         
         ]
      }],
      "Environment":[{
         "Attribute":[
         	{
				"AttributeId": "urn:oasis:names:tc:xacml:3.0:attribute-category:environment",
				"Value": "http://example.com/buy",
				"DataType": "http://www.w3.org/2001/XMLSchema#anyURI"
			}         
         ]
      }]
   }
}

**Comment by cdanger** [comment]
Wrong project I think. The `validateXacmlJson` method and `src/test/resources/xacml.samples/Requests` are not in java-xacml-sdk but [xacml-json-model](https://github.com/authzforce/xacml-json-model) project. Could you re-create the issue here?
Thanks.
