### ISSUE TITLE
Domain ID not used in URI

### ISSUE THREAD

**Issue by DemianTinkiel** [authzforce/java-xacml-sdk#3]
Hi. Looking at Development branch I see that the URI generated is
```
POST Request to URL: http://127.0.0.1:6666/pdp of type application/xml
```
but according to [authzforce docs](https://authzforce-ce-fiware.readthedocs.io/en/release-8.1.0/UserAndProgrammersGuide.html?highlight=Environment%20Category#policy-decision-api) it should be 
```
POST Request to URL: http://127.0.0.1:6666//domains/{domainId}/pdp of type application/xml
```
Doing the same call as in the tests against a real server gives me 404 but if I do
```
    private static final String PDP_ENDPOINT = "http://127.0.0.1:6666/domains/xQOui4BcEemkJAJCrBEAAg";

XacmlSdkImpl myXacml = new XacmlSdkImpl(URI.create(PDP_ENDPOINT), domainName, null);
            responses = myXacml.getAuthZ(subjectCat, resourceCat, actionCategory, environmentCategory);
```
I get  a valid response
looking at `org.ow2.authzforce.sdk.core.Net` it seems `domainId` is never used for anything other than logs

Am I doing something wrong or misunderstanding how it works?

Thanks in advance

**Comment by DemianTinkiel** [comment]
This can be solved with
```
JAXRSClientFactory.create(String.valueOf(this.serverEndpoint), DomainsResource.class). domainsResource.getDomainResource(this.domainId)
```
in `org.ow2.authzforce.sdk.core.Net`

**Comment by hargathor** [comment]
I honestly don't remember why I introduced domainId as a required parameter in the `Net` class. I probably had something in mind at the time
As you said it is only used in the logs for the time being
