### ISSUE TITLE
XACML 3 JSON Profile Support?

### ISSUE THREAD

**Issue by securedimensions** [authzforce/java-xacml-sdk#33]
I'd like to use the SDK to send / receive JSON formatted request / response. But, it seems that only XML is supported. Is that correct?

**Comment by cdanger** [comment]
Yes, only XML is supported by this SDK. We don't provide any similar SDK for JSON. However, I can suggest the following (based on what we've been doing so far):
- Use a template engine to create the XACML/JSON request, e.g. Freemarker, Velocity... (see the example of Freemarker template down below).
- Use the [xacml-json-model project](https://github.com/authzforce/xacml-json-model#xacmljson-request-and-response-json-schema-xacmljson-profile-standard-and-validation) (`authzforce-ce-xacml-json-model` on Maven Central) to validate XACML/JSON requests and responses with JSON schema (according to the JSON Profile of XACML), and rely on the [LimitsCheckingJSONObject](https://javadoc.io/doc/org.ow2.authzforce/authzforce-ce-xacml-json-model/latest/org/ow2/authzforce/xacml/json/model/LimitsCheckingJSONObject.html) provided by this project for safe JSON parsing, or directly on `org.json.JSONObject` class if you don't care.

Example of Freemarker template of XACML/JSON request (`username`, `user_roles`, `request_method`, `request_uri` required as template variables):

```json
{
    "Request":
    {
        "Category":
        [
            {
                "CategoryId": "urn:oasis:names:tc:xacml:1.0:subject-category:access-subject",
                "Attribute":
                [
               		{
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:subject:subject-id",
                        "DataType":"http://www.w3.org/2001/XMLSchema#string",
                       "Value": "<#if username??>${username}<#else></#if>"
                    }
                	<#if user_roles??>
                	,
                    {
                        "AttributeId": "urn:oasis:names:tc:xacml:2.0:subject:role",
                        "DataType":"http://www.w3.org/2001/XMLSchema#string",
                        "Value": [<#list user_roles as role>"${role}"<#sep>,</#sep></#list>]
                    }
                    </#if>
                ]
            },
            {
                "CategoryId": "urn:oasis:names:tc:xacml:3.0:attribute-category:action",
                "Attribute":
                [
                    {
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:action:action-id",
                        "DataType":"http://www.w3.org/2001/XMLSchema#string",
                        "Value": "${request_method}"
                    }
                ]
            },
            {
                "CategoryId": "urn:oasis:names:tc:xacml:3.0:attribute-category:resource",
                "Attribute":
                [
                    {
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:resource:resource-id",
                        "DataType":"http://www.w3.org/2001/XMLSchema#string",
                        "Value": "${request_uri}"
                    }
                ]
            }
        ]
    }
}
```

**Comment by securedimensions** [comment]
Thank you for the quick response and the suggestion. 

 

The main requirement for using JSON over XML is performance. So, the general use case does not “care” about the safety. But, it’s good to know that the option exists…

 

From: Cyril Dangerville ***@***.***>
Reply-To: authzforce/java-xacml-sdk ***@***.***>
Date: Tuesday, 15. March 2022 at 23:29
To: authzforce/java-xacml-sdk ***@***.***>
Cc: Andreas Matheus ***@***.***>, Author ***@***.***>
Subject: Re: [authzforce/java-xacml-sdk] XACML 3 JSON Profile Support? (Issue #33)

 

Yes, only XML is supported by this SDK. We don't provide any similar SDK for JSON. However, I can suggest the following (based on what we've been doing so far):

·         Use a template engine to create the XACML/JSON request, e.g. Freemarker, Velocity... (see the example of Freemarker template down below).

·         Use the xacml-json-model project (authzforce-ce-xacml-json-model on Maven Central) to validate XACML/JSON requests and responses with JSON schema (according to the JSON Profile of XACML), and rely on the LimitsCheckingJSONObject provided by this project for safe JSON parsing, or directly on org.json.JSONObject class if you don't care.

Example of Freemarker template of XACML/JSON request (username, user_roles, request_method, request_uri required as template variables):

{
    "Request":
    {
        "Category":
        [
            {
                "CategoryId": "urn:oasis:names:tc:xacml:1.0:subject-category:access-subject",
                "Attribute":
                [
                         {
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:subject:subject-id",
                        "DataType":"http://www.w3.org/2001/XMLSchema#string",
                       "Value": "<#if username??>${username}<#else></#if>"
                    }
                 <#if user_roles??>
                 ,
                    {
                        "AttributeId": "urn:oasis:names:tc:xacml:2.0:subject:role",
                        "DataType":"http://www.w3.org/2001/XMLSchema#string",
                        "Value": [<#list user_roles as role>"${role}"<#sep>,</#sep></#list>]
                    }
                    </#if>
                ]
            },
            {
                "CategoryId": "urn:oasis:names:tc:xacml:3.0:attribute-category:action",
                "Attribute":
                [
                    {
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:action:action-id",
                        "DataType":"http://www.w3.org/2001/XMLSchema#string",
                        "Value": "${request_method}"
                    }
                ]
            },
            {
                "CategoryId": "urn:oasis:names:tc:xacml:3.0:attribute-category:resource",
                "Attribute":
                [
                    {
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:resource:resource-id",
                        "DataType":"http://www.w3.org/2001/XMLSchema#string",
                        "Value": "${request_uri}"
                    }
                ]
            }
        ]
    }
}
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cdanger** [comment]
Some code example of XACML/JSON request-response can be found in AuthzForce RESTful PDP's [XacmlRestProfileJaxRsTest class](https://github.com/authzforce/restful-pdp/blob/release-6.0.1/cxf-spring-boot-server/src/test/java/org/ow2/authzforce/rest/pdp/cxf/springboot/test/XacmlRestProfileJaxRsTest.java#L79) using Apache CXF JAX-RS client framework. In this code, you may replace `new LimitsCheckingJSONObject(...)` with simply `new JSONObject(...)` .

For better performance, AuthzForce Server also [supports Fast Infoset](https://authzforce-ce-fiware.readthedocs.io/en/latest/InstallationAndAdministrationGuide.html#fast-infoset-mode) which has been tested successfully with Apache CXF JAX-RS client as well (e.g. in [RestServiceTest class](https://github.com/authzforce/server/blob/master/webapp/src/test/java/org/ow2/authzforce/webapp/test/RestServiceTest.java#L451) ).

**Comment by cdanger** [comment]
Closing this issue now as the question has been answered (no support for JSON Profile in SDK). 
However, If you want to make this a feature request, you may create a new issue as such (will be labeled _enhancement_).
