### ISSUE TITLE
allow for use against domainAlias instead of domainId

### ISSUE THREAD

**Issue by DemianTinkiel** [authzforce/java-xacml-sdk#7]
My application might not have any knowledge on authzforce UUID for a given domain (all I'm given is domain name) so ideally I'd like to be able to translate name to UUID

I thing this can be done with `org.ow2.authzforce.rest.api.jaxrs.DomainsResource#getDomains`
so I'd suggest something like
```
private DomainResource setupProxy(boolean doDomainIdTranslation) {
		DomainsResource domainsResource = JAXRSClientFactory.create(String.valueOf(this.serverEndpoint), DomainsResource.class);
		if (doDomainIdTranslation) {
			this.domainId = getDomainIdFromAlias(domainsResource, this.domainId);
		}
...
```
and
```
private String getDomainIdFromAlias(DomainsResource domainsResource, String domainAlias) {
  Resources resources = domainsResource.getDomains(domainAlias);
  return resources.getLinks().get(0).getHref();
}
```
in `org.ow2.authzforce.sdk.core.Net`

**Comment by DemianTinkiel** [comment]
Question would this be considered a break in architecture? I ask because the way I understand it the `GET /domains?externalId` endpoint is considered as part of the Domain Management API according to [docs](https://authzforce-ce-fiware.readthedocs.io/en/latest/UserAndProgrammersGuide.html#domain-management-api)

If this is an acceptable I have a PR that will come in shortly

**Comment by hargathor** [comment]
I think this is acceptable. As you've said the application might not be aware of authzforce UUID.

**Comment by DemianTinkiel** [comment]
@hargathor , excellent. In that case #9 should do the trick.
